#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2021 Mattias Schlenker <ms@mattiasschlenker.de> for tribe29 GmbH
# License: GNU General Public License v2
#
# Reference for details:
# https://docs.checkmk.com/latest/en/devel_check_plugins.html
#
#
# This is the agent/client side script for a "Hello World!" Plugin for CheckMK 2.0
#
# /usr/lib/check_mk_agent/plugins/hello_world
#
# For our "Hello bakery!" example we extended it to read a JSON config file.

from random import random
import json

# Read our config filed:
with open('/etc/check_mk/hello_bakery.json') as json_file:
    cfg = json.load(json_file)

# The section should just use 7bit lowercase characters and underscores. They must 
# match the name set in register.check_plugin(). Make sure to choose a unique name
# to avoid having two plugins with the same name.

print("<<<hello_bakery>>>")

# Just print a (fairly) random number between 0.0 and 100.0, interpreted as
# percentage. The output will be space separated which will be split into tokens
# as CheckMK receives the output. 
#
# hello_bakery 98.41417513129443

print("hello_bakery", random() * 100.0) 
print("user", cfg['user'])

